<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Settings</name>
   <tag></tag>
   <elementGuidId>705d05ea-1d4a-4551-808e-82b9a94158ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
                js-menu-item
                js-menu-item--with-submenu
                js-tour--menu-item-settings
                l-grid-1of1
                c-menu--main-item
                
                u-height--x3
                u-border-radius--zero
                u-padding-left--small
                u-padding-right
                u-flex-box--vertical
                u-color--grey-very-light
                u-text-align--left
            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-background
                u-bottom--x0
                u-left--x0
                u-position--absolute
                u-right--x0
                u-top--x0
                u-print--no-background&quot;]/div[@class=&quot;js-menu
                v3
                c-menu
                u-box-shadow
                u-z-index--sky
                u-position--fixed
                u-height--100x100
                u-background--black
                u-print--never&quot;]/div[@class=&quot;js-menu-scrollable c-menu--scrollable-container&quot;]/div[@class=&quot;gm-scrollbar-container&quot;]/div[@class=&quot;gm-scroll-view&quot;]/div[@class=&quot;c-menu--scrollable-content&quot;]/nav[@class=&quot;js-main-menu&quot;]/ul[1]/li[@class=&quot;l-grid-1of1&quot;]/button[@class=&quot;js-menu-item
                js-menu-item--with-submenu
                js-tour--menu-item-settings
                l-grid-1of1
                c-menu--main-item
                
                u-height--x3
                u-border-radius--zero
                u-padding-left--small
                u-padding-right
                u-flex-box--vertical
                u-color--grey-very-light
                u-text-align--left&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>(//button[@type='button'])[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='root']/div/div[2]/div/div/div[3]/div/nav/ul/li[8]/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statistics'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting'])[1]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Earn free months'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//li[8]/button</value>
   </webElementXpaths>
</WebElementEntity>
